# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Sat Mar 29 19:36:03 2014
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(337, 400)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/res/mainicon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.searchlabelLabel = QtWidgets.QLabel(self.centralwidget)
        self.searchlabelLabel.setObjectName("searchlabelLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.searchlabelLabel)
        self.searchfield = QtWidgets.QLineEdit(self.centralwidget)
        self.searchfield.setObjectName("searchfield")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.searchfield)
        self.verticalLayout.addLayout(self.formLayout)
        self.memberlistwidget = QtWidgets.QListWidget(self.centralwidget)
        self.memberlistwidget.setObjectName("memberlistwidget")
        self.verticalLayout.addWidget(self.memberlistwidget)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.memberinfo = QtWidgets.QTextEdit(self.centralwidget)
        self.memberinfo.setUndoRedoEnabled(True)
        self.memberinfo.setReadOnly(True)
        self.memberinfo.setObjectName("memberinfo")
        self.verticalLayout.addWidget(self.memberinfo)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 337, 25))
        self.menubar.setObjectName("menubar")
        self.menuNew = QtWidgets.QMenu(self.menubar)
        self.menuNew.setObjectName("menuNew")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNewMember = QtWidgets.QAction(MainWindow)
        self.actionNewMember.setObjectName("actionNewMember")
        self.actionNewGroup = QtWidgets.QAction(MainWindow)
        self.actionNewGroup.setObjectName("actionNewGroup")
        self.actionNewPost = QtWidgets.QAction(MainWindow)
        self.actionNewPost.setObjectName("actionNewPost")
        self.actionGrupper = QtWidgets.QAction(MainWindow)
        self.actionGrupper.setObjectName("actionGrupper")
        self.actionPoster = QtWidgets.QAction(MainWindow)
        self.actionPoster.setObjectName("actionPoster")
        self.actionMakeBackup = QtWidgets.QAction(MainWindow)
        self.actionMakeBackup.setObjectName("actionMakeBackup")
        self.actionRestoreFromBackup = QtWidgets.QAction(MainWindow)
        self.actionRestoreFromBackup.setObjectName("actionRestoreFromBackup")
        self.actionAvdelningar = QtWidgets.QAction(MainWindow)
        self.actionAvdelningar.setObjectName("actionAvdelningar")
        self.actionNewDepartment = QtWidgets.QAction(MainWindow)
        self.actionNewDepartment.setObjectName("actionNewDepartment")
        self.actionRemoveMember = QtWidgets.QAction(MainWindow)
        self.actionRemoveMember.setObjectName("actionRemoveMember")
        self.actionEditMember = QtWidgets.QAction(MainWindow)
        self.actionEditMember.setObjectName("actionEditMember")
        self.menuNew.addAction(self.actionNewMember)
        self.menuNew.addAction(self.actionNewGroup)
        self.menuNew.addAction(self.actionNewPost)
        self.menuNew.addAction(self.actionNewDepartment)
        self.menuEdit.addAction(self.actionGrupper)
        self.menuEdit.addAction(self.actionPoster)
        self.menuEdit.addAction(self.actionAvdelningar)
        self.menuFile.addAction(self.actionMakeBackup)
        self.menuFile.addAction(self.actionRestoreFromBackup)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuNew.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.searchlabelLabel.setBuddy(self.searchfield)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.searchlabelLabel.setText(_translate("MainWindow", "Sök"))
        self.label.setText(_translate("MainWindow", "Info"))
        self.menuNew.setTitle(_translate("MainWindow", "Ny"))
        self.menuEdit.setTitle(_translate("MainWindow", "Editera"))
        self.menuFile.setTitle(_translate("MainWindow", "Fil"))
        self.actionNewMember.setText(_translate("MainWindow", "Medlem"))
        self.actionNewMember.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionNewGroup.setText(_translate("MainWindow", "Grupp"))
        self.actionNewPost.setText(_translate("MainWindow", "Post"))
        self.actionGrupper.setText(_translate("MainWindow", "Grupper"))
        self.actionPoster.setText(_translate("MainWindow", "Poster"))
        self.actionMakeBackup.setText(_translate("MainWindow", "Gör säkerhetskopia"))
        self.actionMakeBackup.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionRestoreFromBackup.setText(_translate("MainWindow", "Återställ databas"))
        self.actionRestoreFromBackup.setShortcut(_translate("MainWindow", "Ctrl+L"))
        self.actionAvdelningar.setText(_translate("MainWindow", "Avdelningar"))
        self.actionNewDepartment.setText(_translate("MainWindow", "Avdelning"))
        self.actionRemoveMember.setText(_translate("MainWindow", "Ta bort medlem"))
        self.actionEditMember.setText(_translate("MainWindow", "Editera Medlem"))

import svaksvat_rc
