# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'memberedit.ui'
#
# Created: Sat Sep  8 11:28:55 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MemberEdit(object):
    def setupUi(self, MemberEdit):
        MemberEdit.setObjectName(_fromUtf8("MemberEdit"))
        MemberEdit.resize(848, 595)
        self.gridLayout = QtGui.QGridLayout(MemberEdit)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.allaFornamnLabel = QtGui.QLabel(MemberEdit)
        self.allaFornamnLabel.setObjectName(_fromUtf8("allaFornamnLabel"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.allaFornamnLabel)
        self.givenNames_fld = QtGui.QLineEdit(MemberEdit)
        self.givenNames_fld.setObjectName(_fromUtf8("givenNames_fld"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.givenNames_fld)
        self.efternamnLabel = QtGui.QLabel(MemberEdit)
        self.efternamnLabel.setObjectName(_fromUtf8("efternamnLabel"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.efternamnLabel)
        self.surName_fld = QtGui.QLineEdit(MemberEdit)
        self.surName_fld.setObjectName(_fromUtf8("surName_fld"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.surName_fld)
        self.tidigareEfternamnLabel = QtGui.QLabel(MemberEdit)
        self.tidigareEfternamnLabel.setObjectName(_fromUtf8("tidigareEfternamnLabel"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.tidigareEfternamnLabel)
        self.maidenName_fld = QtGui.QLineEdit(MemberEdit)
        self.maidenName_fld.setObjectName(_fromUtf8("maidenName_fld"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.maidenName_fld)
        self.tilltalsnamnLabel = QtGui.QLabel(MemberEdit)
        self.tilltalsnamnLabel.setObjectName(_fromUtf8("tilltalsnamnLabel"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.tilltalsnamnLabel)
        self.preferredName_fld = QtGui.QLineEdit(MemberEdit)
        self.preferredName_fld.setObjectName(_fromUtf8("preferredName_fld"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.preferredName_fld)
        self.studienummerLabel = QtGui.QLabel(MemberEdit)
        self.studienummerLabel.setObjectName(_fromUtf8("studienummerLabel"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.studienummerLabel)
        self.studentId_fld = QtGui.QLineEdit(MemberEdit)
        self.studentId_fld.setObjectName(_fromUtf8("studentId_fld"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.studentId_fld)
        self.avlidenLabel = QtGui.QLabel(MemberEdit)
        self.avlidenLabel.setObjectName(_fromUtf8("avlidenLabel"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.LabelRole, self.avlidenLabel)
        self.dead_fld = QtGui.QCheckBox(MemberEdit)
        self.dead_fld.setObjectName(_fromUtf8("dead_fld"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.dead_fld)
        self.fDelsedatumLabel = QtGui.QLabel(MemberEdit)
        self.fDelsedatumLabel.setObjectName(_fromUtf8("fDelsedatumLabel"))
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.LabelRole, self.fDelsedatumLabel)
        self.birthDate_fld = QtGui.QDateEdit(MemberEdit)
        self.birthDate_fld.setCalendarPopup(True)
        self.birthDate_fld.setObjectName(_fromUtf8("birthDate_fld"))
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.FieldRole, self.birthDate_fld)
        self.nationalitetLabel = QtGui.QLabel(MemberEdit)
        self.nationalitetLabel.setObjectName(_fromUtf8("nationalitetLabel"))
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.LabelRole, self.nationalitetLabel)
        self.nationality_fld = QtGui.QLineEdit(MemberEdit)
        self.nationality_fld.setObjectName(_fromUtf8("nationality_fld"))
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.FieldRole, self.nationality_fld)
        self.kNLabel = QtGui.QLabel(MemberEdit)
        self.kNLabel.setObjectName(_fromUtf8("kNLabel"))
        self.formLayout_2.setWidget(8, QtGui.QFormLayout.LabelRole, self.kNLabel)
        self.gender_fld = QtGui.QComboBox(MemberEdit)
        self.gender_fld.setObjectName(_fromUtf8("gender_fld"))
        self.formLayout_2.setWidget(8, QtGui.QFormLayout.FieldRole, self.gender_fld)
        self.subscribedToModulen_fld = QtGui.QLabel(MemberEdit)
        self.subscribedToModulen_fld.setObjectName(_fromUtf8("subscribedToModulen_fld"))
        self.formLayout_2.setWidget(10, QtGui.QFormLayout.LabelRole, self.subscribedToModulen_fld)
        self.subscribedToModulen_fld_checkbox = QtGui.QCheckBox(MemberEdit)
        self.subscribedToModulen_fld_checkbox.setObjectName(_fromUtf8("subscribedToModulen_fld_checkbox"))
        self.formLayout_2.setWidget(10, QtGui.QFormLayout.FieldRole, self.subscribedToModulen_fld_checkbox)
        self.username_fldLabel = QtGui.QLabel(MemberEdit)
        self.username_fldLabel.setObjectName(_fromUtf8("username_fldLabel"))
        self.formLayout_2.setWidget(11, QtGui.QFormLayout.LabelRole, self.username_fldLabel)
        self.username_fld = QtGui.QLineEdit(MemberEdit)
        self.username_fld.setObjectName(_fromUtf8("username_fld"))
        self.formLayout_2.setWidget(11, QtGui.QFormLayout.FieldRole, self.username_fld)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.notes_fldLabel = QtGui.QLabel(MemberEdit)
        self.notes_fldLabel.setObjectName(_fromUtf8("notes_fldLabel"))
        self.verticalLayout.addWidget(self.notes_fldLabel)
        self.notes_fld = QtGui.QPlainTextEdit(MemberEdit)
        self.notes_fld.setObjectName(_fromUtf8("notes_fld"))
        self.verticalLayout.addWidget(self.notes_fld)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.gatuadressLabel = QtGui.QLabel(MemberEdit)
        self.gatuadressLabel.setObjectName(_fromUtf8("gatuadressLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.gatuadressLabel)
        self.streetAddress_fld = QtGui.QLineEdit(MemberEdit)
        self.streetAddress_fld.setObjectName(_fromUtf8("streetAddress_fld"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.streetAddress_fld)
        self.postnummerLabel = QtGui.QLabel(MemberEdit)
        self.postnummerLabel.setObjectName(_fromUtf8("postnummerLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.postnummerLabel)
        self.postalCode_fld = QtGui.QLineEdit(MemberEdit)
        self.postalCode_fld.setObjectName(_fromUtf8("postalCode_fld"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.postalCode_fld)
        self.stadLabel = QtGui.QLabel(MemberEdit)
        self.stadLabel.setObjectName(_fromUtf8("stadLabel"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.stadLabel)
        self.city_fld = QtGui.QLineEdit(MemberEdit)
        self.city_fld.setObjectName(_fromUtf8("city_fld"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.city_fld)
        self.landLabel = QtGui.QLabel(MemberEdit)
        self.landLabel.setObjectName(_fromUtf8("landLabel"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.landLabel)
        self.country_fld = QtGui.QLineEdit(MemberEdit)
        self.country_fld.setObjectName(_fromUtf8("country_fld"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.country_fld)
        self.telefonLabel = QtGui.QLabel(MemberEdit)
        self.telefonLabel.setObjectName(_fromUtf8("telefonLabel"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.telefonLabel)
        self.phone_fld = QtGui.QLineEdit(MemberEdit)
        self.phone_fld.setObjectName(_fromUtf8("phone_fld"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.phone_fld)
        self.emailLabel = QtGui.QLabel(MemberEdit)
        self.emailLabel.setObjectName(_fromUtf8("emailLabel"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.emailLabel)
        self.email_fld = QtGui.QLineEdit(MemberEdit)
        self.email_fld.setObjectName(_fromUtf8("email_fld"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.email_fld)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.tabWidget = QtGui.QTabWidget(MemberEdit)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_3.addWidget(self.label)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.groupView = QtGui.QListView(self.tab)
        self.groupView.setObjectName(_fromUtf8("groupView"))
        self.horizontalLayout_7.addWidget(self.groupView)
        self.removeGroupButton = QtGui.QPushButton(self.tab)
        self.removeGroupButton.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/res/list_remove.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.removeGroupButton.setIcon(icon)
        self.removeGroupButton.setObjectName(_fromUtf8("removeGroupButton"))
        self.horizontalLayout_7.addWidget(self.removeGroupButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.group_comboBox = QtGui.QComboBox(self.tab)
        self.group_comboBox.setEditable(True)
        self.group_comboBox.setInsertPolicy(QtGui.QComboBox.InsertAlphabetically)
        self.group_comboBox.setObjectName(_fromUtf8("group_comboBox"))
        self.horizontalLayout_2.addWidget(self.group_comboBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_3.addWidget(self.label_2)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.postView = QtGui.QListView(self.tab)
        self.postView.setObjectName(_fromUtf8("postView"))
        self.horizontalLayout_8.addWidget(self.postView)
        self.removePostButton = QtGui.QPushButton(self.tab)
        self.removePostButton.setText(_fromUtf8(""))
        self.removePostButton.setIcon(icon)
        self.removePostButton.setObjectName(_fromUtf8("removePostButton"))
        self.horizontalLayout_8.addWidget(self.removePostButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_3.addWidget(self.label_4)
        self.post_comboBox = QtGui.QComboBox(self.tab)
        self.post_comboBox.setEditable(True)
        self.post_comboBox.setObjectName(_fromUtf8("post_comboBox"))
        self.horizontalLayout_3.addWidget(self.post_comboBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.tab_6)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.billAccountStatusLabel = QtGui.QLabel(self.tab_6)
        self.billAccountStatusLabel.setObjectName(_fromUtf8("billAccountStatusLabel"))
        self.gridLayout_2.addWidget(self.billAccountStatusLabel, 1, 1, 1, 1)
        self.label_18 = QtGui.QLabel(self.tab_6)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_2.addWidget(self.label_18, 0, 0, 1, 1)
        self.label_19 = QtGui.QLabel(self.tab_6)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_2.addWidget(self.label_19, 2, 0, 1, 1)
        self.label_20 = QtGui.QLabel(self.tab_6)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_2.addWidget(self.label_20, 1, 0, 1, 1)
        self.billAccountCreditLabel = QtGui.QLabel(self.tab_6)
        self.billAccountCreditLabel.setObjectName(_fromUtf8("billAccountCreditLabel"))
        self.gridLayout_2.addWidget(self.billAccountCreditLabel, 2, 1, 1, 1)
        self.ldapAccountStatusLabel = QtGui.QLabel(self.tab_6)
        self.ldapAccountStatusLabel.setObjectName(_fromUtf8("ldapAccountStatusLabel"))
        self.gridLayout_2.addWidget(self.ldapAccountStatusLabel, 0, 1, 1, 1)
        self.label_21 = QtGui.QLabel(self.tab_6)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_2.addWidget(self.label_21, 3, 0, 1, 1)
        self.ldapGroupsLabel = QtGui.QPlainTextEdit(self.tab_6)
        self.ldapGroupsLabel.setEnabled(True)
        self.ldapGroupsLabel.setReadOnly(True)
        self.ldapGroupsLabel.setPlainText(_fromUtf8(""))
        self.ldapGroupsLabel.setBackgroundVisible(False)
        self.ldapGroupsLabel.setObjectName(_fromUtf8("ldapGroupsLabel"))
        self.gridLayout_2.addWidget(self.ldapGroupsLabel, 3, 1, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_2)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.createUserAccountsButton = QtGui.QPushButton(self.tab_6)
        self.createUserAccountsButton.setObjectName(_fromUtf8("createUserAccountsButton"))
        self.verticalLayout_7.addWidget(self.createUserAccountsButton)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.ldapPasswordLineEdit = QtGui.QLineEdit(self.tab_6)
        self.ldapPasswordLineEdit.setEchoMode(QtGui.QLineEdit.Password)
        self.ldapPasswordLineEdit.setObjectName(_fromUtf8("ldapPasswordLineEdit"))
        self.horizontalLayout_21.addWidget(self.ldapPasswordLineEdit)
        self.changeLdapPasswordButton = QtGui.QPushButton(self.tab_6)
        self.changeLdapPasswordButton.setObjectName(_fromUtf8("changeLdapPasswordButton"))
        self.horizontalLayout_21.addWidget(self.changeLdapPasswordButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_21)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_10 = QtGui.QLabel(self.tab_2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_5.addWidget(self.label_10)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.departmentView = QtGui.QListView(self.tab_2)
        self.departmentView.setObjectName(_fromUtf8("departmentView"))
        self.horizontalLayout_12.addWidget(self.departmentView)
        self.removeDepartmentButton = QtGui.QPushButton(self.tab_2)
        self.removeDepartmentButton.setText(_fromUtf8(""))
        self.removeDepartmentButton.setIcon(icon)
        self.removeDepartmentButton.setObjectName(_fromUtf8("removeDepartmentButton"))
        self.horizontalLayout_12.addWidget(self.removeDepartmentButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_9 = QtGui.QLabel(self.tab_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_6.addWidget(self.label_9)
        self.department_comboBox = QtGui.QComboBox(self.tab_2)
        self.department_comboBox.setEditable(True)
        self.department_comboBox.setInsertPolicy(QtGui.QComboBox.InsertAlphabetically)
        self.department_comboBox.setObjectName(_fromUtf8("department_comboBox"))
        self.horizontalLayout_6.addWidget(self.department_comboBox)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.label_12 = QtGui.QLabel(self.tab_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_5.addWidget(self.label_12)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.membershipView = QtGui.QListView(self.tab_2)
        self.membershipView.setObjectName(_fromUtf8("membershipView"))
        self.horizontalLayout_13.addWidget(self.membershipView)
        self.removeMembershipButton = QtGui.QPushButton(self.tab_2)
        self.removeMembershipButton.setText(_fromUtf8(""))
        self.removeMembershipButton.setIcon(icon)
        self.removeMembershipButton.setObjectName(_fromUtf8("removeMembershipButton"))
        self.horizontalLayout_13.addWidget(self.removeMembershipButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.pushButton = QtGui.QPushButton(self.tab_2)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_14.addWidget(self.pushButton)
        self.pushButton_2 = QtGui.QPushButton(self.tab_2)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_14.addWidget(self.pushButton_2)
        self.pushButton_3 = QtGui.QPushButton(self.tab_2)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout_14.addWidget(self.pushButton_3)
        self.pushButton_4 = QtGui.QPushButton(self.tab_2)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.horizontalLayout_14.addWidget(self.pushButton_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_14)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(MemberEdit)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.allaFornamnLabel.setBuddy(self.givenNames_fld)
        self.efternamnLabel.setBuddy(self.surName_fld)
        self.tidigareEfternamnLabel.setBuddy(self.maidenName_fld)
        self.tilltalsnamnLabel.setBuddy(self.preferredName_fld)
        self.studienummerLabel.setBuddy(self.studentId_fld)
        self.avlidenLabel.setBuddy(self.dead_fld)
        self.fDelsedatumLabel.setBuddy(self.birthDate_fld)
        self.nationalitetLabel.setBuddy(self.nationality_fld)
        self.kNLabel.setBuddy(self.gender_fld)
        self.subscribedToModulen_fld.setBuddy(self.subscribedToModulen_fld_checkbox)
        self.username_fldLabel.setBuddy(self.username_fld)
        self.notes_fldLabel.setBuddy(self.notes_fld)
        self.gatuadressLabel.setBuddy(self.streetAddress_fld)
        self.postnummerLabel.setBuddy(self.postalCode_fld)
        self.stadLabel.setBuddy(self.city_fld)
        self.landLabel.setBuddy(self.country_fld)
        self.telefonLabel.setBuddy(self.phone_fld)
        self.emailLabel.setBuddy(self.email_fld)
        self.label_3.setBuddy(self.group_comboBox)
        self.label_4.setBuddy(self.post_comboBox)
        self.label_9.setBuddy(self.group_comboBox)

        self.retranslateUi(MemberEdit)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), MemberEdit.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), MemberEdit.reject)
        QtCore.QMetaObject.connectSlotsByName(MemberEdit)
        MemberEdit.setTabOrder(self.givenNames_fld, self.surName_fld)
        MemberEdit.setTabOrder(self.surName_fld, self.maidenName_fld)
        MemberEdit.setTabOrder(self.maidenName_fld, self.preferredName_fld)
        MemberEdit.setTabOrder(self.preferredName_fld, self.studentId_fld)
        MemberEdit.setTabOrder(self.studentId_fld, self.dead_fld)
        MemberEdit.setTabOrder(self.dead_fld, self.birthDate_fld)
        MemberEdit.setTabOrder(self.birthDate_fld, self.nationality_fld)
        MemberEdit.setTabOrder(self.nationality_fld, self.gender_fld)
        MemberEdit.setTabOrder(self.gender_fld, self.subscribedToModulen_fld_checkbox)
        MemberEdit.setTabOrder(self.subscribedToModulen_fld_checkbox, self.username_fld)
        MemberEdit.setTabOrder(self.username_fld, self.notes_fld)
        MemberEdit.setTabOrder(self.notes_fld, self.buttonBox)
        MemberEdit.setTabOrder(self.buttonBox, self.streetAddress_fld)
        MemberEdit.setTabOrder(self.streetAddress_fld, self.postalCode_fld)
        MemberEdit.setTabOrder(self.postalCode_fld, self.city_fld)
        MemberEdit.setTabOrder(self.city_fld, self.country_fld)
        MemberEdit.setTabOrder(self.country_fld, self.phone_fld)
        MemberEdit.setTabOrder(self.phone_fld, self.email_fld)
        MemberEdit.setTabOrder(self.email_fld, self.groupView)
        MemberEdit.setTabOrder(self.groupView, self.removeGroupButton)
        MemberEdit.setTabOrder(self.removeGroupButton, self.group_comboBox)
        MemberEdit.setTabOrder(self.group_comboBox, self.postView)
        MemberEdit.setTabOrder(self.postView, self.removePostButton)
        MemberEdit.setTabOrder(self.removePostButton, self.post_comboBox)

    def retranslateUi(self, MemberEdit):
        MemberEdit.setWindowTitle(QtGui.QApplication.translate("MemberEdit", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.allaFornamnLabel.setText(QtGui.QApplication.translate("MemberEdit", "Alla förnamn", None, QtGui.QApplication.UnicodeUTF8))
        self.efternamnLabel.setText(QtGui.QApplication.translate("MemberEdit", "Efternamn", None, QtGui.QApplication.UnicodeUTF8))
        self.tidigareEfternamnLabel.setText(QtGui.QApplication.translate("MemberEdit", "Tidigare efternamn", None, QtGui.QApplication.UnicodeUTF8))
        self.tilltalsnamnLabel.setText(QtGui.QApplication.translate("MemberEdit", "Tilltalsnamn", None, QtGui.QApplication.UnicodeUTF8))
        self.studienummerLabel.setText(QtGui.QApplication.translate("MemberEdit", "Studienummer", None, QtGui.QApplication.UnicodeUTF8))
        self.avlidenLabel.setText(QtGui.QApplication.translate("MemberEdit", "Avliden", None, QtGui.QApplication.UnicodeUTF8))
        self.fDelsedatumLabel.setText(QtGui.QApplication.translate("MemberEdit", "Födelsedatum", None, QtGui.QApplication.UnicodeUTF8))
        self.nationalitetLabel.setText(QtGui.QApplication.translate("MemberEdit", "Nationalitet", None, QtGui.QApplication.UnicodeUTF8))
        self.kNLabel.setText(QtGui.QApplication.translate("MemberEdit", "Kön", None, QtGui.QApplication.UnicodeUTF8))
        self.subscribedToModulen_fld.setText(QtGui.QApplication.translate("MemberEdit", "Vill ha Modulen", None, QtGui.QApplication.UnicodeUTF8))
        self.username_fldLabel.setText(QtGui.QApplication.translate("MemberEdit", "Användarnamn", None, QtGui.QApplication.UnicodeUTF8))
        self.notes_fldLabel.setText(QtGui.QApplication.translate("MemberEdit", "Kommentarer (Max 255 st. tecken)", None, QtGui.QApplication.UnicodeUTF8))
        self.gatuadressLabel.setText(QtGui.QApplication.translate("MemberEdit", "Gatuadress", None, QtGui.QApplication.UnicodeUTF8))
        self.postnummerLabel.setText(QtGui.QApplication.translate("MemberEdit", "Postnummer", None, QtGui.QApplication.UnicodeUTF8))
        self.stadLabel.setText(QtGui.QApplication.translate("MemberEdit", "Stad", None, QtGui.QApplication.UnicodeUTF8))
        self.landLabel.setText(QtGui.QApplication.translate("MemberEdit", "Land", None, QtGui.QApplication.UnicodeUTF8))
        self.telefonLabel.setText(QtGui.QApplication.translate("MemberEdit", "Telefon", None, QtGui.QApplication.UnicodeUTF8))
        self.emailLabel.setText(QtGui.QApplication.translate("MemberEdit", "Email", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MemberEdit", "Grupper:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MemberEdit", "Lägg till grupp:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MemberEdit", "Poster:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MemberEdit", "Lägg till post:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MemberEdit", "TF-Aktivitet", None, QtGui.QApplication.UnicodeUTF8))
        self.billAccountStatusLabel.setText(QtGui.QApplication.translate("MemberEdit", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MemberEdit", "LDAP-konto", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MemberEdit", "BILL-kredit", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MemberEdit", "BILL-konto", None, QtGui.QApplication.UnicodeUTF8))
        self.billAccountCreditLabel.setText(QtGui.QApplication.translate("MemberEdit", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.ldapAccountStatusLabel.setText(QtGui.QApplication.translate("MemberEdit", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MemberEdit", "LDAP-Grupper", None, QtGui.QApplication.UnicodeUTF8))
        self.createUserAccountsButton.setText(QtGui.QApplication.translate("MemberEdit", "Skapa användarkonton", None, QtGui.QApplication.UnicodeUTF8))
        self.changeLdapPasswordButton.setText(QtGui.QApplication.translate("MemberEdit", "Byt lösenord", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), QtGui.QApplication.translate("MemberEdit", "Användarkonton", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MemberEdit", "Studieinriktning:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MemberEdit", "Lägg till studieinriktning:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MemberEdit", "TF Medlemskapstyper:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MemberEdit", "Phux", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("MemberEdit", "Ordinarie", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("MemberEdit", "StÄlM", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setText(QtGui.QApplication.translate("MemberEdit", "Ej medlem", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MemberEdit", "Aalto och TF medlemskap", None, QtGui.QApplication.UnicodeUTF8))

import svaksvat_rc
