# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'membershipedit.ui'
#
# Created: Sat Mar 29 19:32:56 2014
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MembershipEdit(object):
    def setupUi(self, MembershipEdit):
        MembershipEdit.setObjectName("MembershipEdit")
        MembershipEdit.resize(244, 330)
        MembershipEdit.setWindowTitle("")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(MembershipEdit)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.mandate_GroupBox = QtWidgets.QGroupBox(MembershipEdit)
        self.mandate_GroupBox.setObjectName("mandate_GroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.mandate_GroupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.wholeyear_radioButton = QtWidgets.QRadioButton(self.mandate_GroupBox)
        self.wholeyear_radioButton.setObjectName("wholeyear_radioButton")
        self.verticalLayout_2.addWidget(self.wholeyear_radioButton)
        self.laborday_radioButton = QtWidgets.QRadioButton(self.mandate_GroupBox)
        self.laborday_radioButton.setObjectName("laborday_radioButton")
        self.verticalLayout_2.addWidget(self.laborday_radioButton)
        self.onwards_radioButton = QtWidgets.QRadioButton(self.mandate_GroupBox)
        self.onwards_radioButton.setObjectName("onwards_radioButton")
        self.verticalLayout_2.addWidget(self.onwards_radioButton)
        self.otherMandate_radioButton = QtWidgets.QRadioButton(self.mandate_GroupBox)
        self.otherMandate_radioButton.setObjectName("otherMandate_radioButton")
        self.verticalLayout_2.addWidget(self.otherMandate_radioButton)
        self.verticalLayout.addWidget(self.mandate_GroupBox)
        self.startAndEndTimeWidget = QtWidgets.QWidget(MembershipEdit)
        self.startAndEndTimeWidget.setObjectName("startAndEndTimeWidget")
        self.startEndLayout = QtWidgets.QFormLayout(self.startAndEndTimeWidget)
        self.startEndLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.startEndLayout.setContentsMargins(0, 0, 0, 0)
        self.startEndLayout.setObjectName("startEndLayout")
        self.startdatumLabel_2 = QtWidgets.QLabel(self.startAndEndTimeWidget)
        self.startdatumLabel_2.setObjectName("startdatumLabel_2")
        self.startEndLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.startdatumLabel_2)
        self.startTime_fld = QtWidgets.QDateEdit(self.startAndEndTimeWidget)
        self.startTime_fld.setObjectName("startTime_fld")
        self.startEndLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.startTime_fld)
        self.endTimeLabel = QtWidgets.QLabel(self.startAndEndTimeWidget)
        self.endTimeLabel.setObjectName("endTimeLabel")
        self.startEndLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.endTimeLabel)
        self.endTime_fld = QtWidgets.QDateEdit(self.startAndEndTimeWidget)
        self.endTime_fld.setObjectName("endTime_fld")
        self.startEndLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.endTime_fld)
        self.verticalLayout.addWidget(self.startAndEndTimeWidget)
        self.startYearWidget = QtWidgets.QWidget(MembershipEdit)
        self.startYearWidget.setObjectName("startYearWidget")
        self.startYearLayout = QtWidgets.QFormLayout(self.startYearWidget)
        self.startYearLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.startYearLayout.setContentsMargins(0, 0, 0, 0)
        self.startYearLayout.setObjectName("startYearLayout")
        self.frNRLabel = QtWidgets.QLabel(self.startYearWidget)
        self.frNRLabel.setObjectName("frNRLabel")
        self.startYearLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.frNRLabel)
        self.startYear_spinBox = QtWidgets.QSpinBox(self.startYearWidget)
        self.startYear_spinBox.setObjectName("startYear_spinBox")
        self.startYearLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.startYear_spinBox)
        self.verticalLayout.addWidget(self.startYearWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(MembershipEdit)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.verticalLayout_3.addLayout(self.verticalLayout)

        self.retranslateUi(MembershipEdit)
        self.wholeyear_radioButton.toggled['bool'].connect(self.startYearWidget.setVisible)
        self.laborday_radioButton.toggled['bool'].connect(self.startYearWidget.setVisible)
        self.laborday_radioButton.toggled['bool'].connect(self.startAndEndTimeWidget.setHidden)
        self.onwards_radioButton.toggled['bool'].connect(self.endTime_fld.setHidden)
        self.wholeyear_radioButton.toggled['bool'].connect(self.startAndEndTimeWidget.setHidden)
        self.onwards_radioButton.toggled['bool'].connect(self.endTimeLabel.setHidden)
        QtCore.QMetaObject.connectSlotsByName(MembershipEdit)

    def retranslateUi(self, MembershipEdit):
        _translate = QtCore.QCoreApplication.translate
        self.mandate_GroupBox.setTitle(_translate("MembershipEdit", "Mandattid"))
        self.wholeyear_radioButton.setText(_translate("MembershipEdit", "Hela året"))
        self.laborday_radioButton.setText(_translate("MembershipEdit", "Vapp till vapp"))
        self.onwards_radioButton.setText(_translate("MembershipEdit", "Obestämd tid"))
        self.otherMandate_radioButton.setText(_translate("MembershipEdit", "Annan tid"))
        self.startdatumLabel_2.setText(_translate("MembershipEdit", "Startdatum"))
        self.endTimeLabel.setText(_translate("MembershipEdit", "Slutdatum"))
        self.frNRLabel.setText(_translate("MembershipEdit", "Från år"))

