# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'memberedit.ui'
#
# Created: Sat Mar 29 19:36:28 2014
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MemberEdit(object):
    def setupUi(self, MemberEdit):
        MemberEdit.setObjectName("MemberEdit")
        MemberEdit.resize(981, 655)
        self.gridLayout = QtWidgets.QGridLayout(MemberEdit)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.allaFornamnLabel = QtWidgets.QLabel(MemberEdit)
        self.allaFornamnLabel.setObjectName("allaFornamnLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.allaFornamnLabel)
        self.givenNames_fld = QtWidgets.QLineEdit(MemberEdit)
        self.givenNames_fld.setObjectName("givenNames_fld")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.givenNames_fld)
        self.efternamnLabel = QtWidgets.QLabel(MemberEdit)
        self.efternamnLabel.setObjectName("efternamnLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.efternamnLabel)
        self.surName_fld = QtWidgets.QLineEdit(MemberEdit)
        self.surName_fld.setObjectName("surName_fld")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.surName_fld)
        self.tidigareEfternamnLabel = QtWidgets.QLabel(MemberEdit)
        self.tidigareEfternamnLabel.setObjectName("tidigareEfternamnLabel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.tidigareEfternamnLabel)
        self.maidenName_fld = QtWidgets.QLineEdit(MemberEdit)
        self.maidenName_fld.setObjectName("maidenName_fld")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.maidenName_fld)
        self.tilltalsnamnLabel = QtWidgets.QLabel(MemberEdit)
        self.tilltalsnamnLabel.setObjectName("tilltalsnamnLabel")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.tilltalsnamnLabel)
        self.preferredName_fld = QtWidgets.QLineEdit(MemberEdit)
        self.preferredName_fld.setObjectName("preferredName_fld")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.preferredName_fld)
        self.studienummerLabel = QtWidgets.QLabel(MemberEdit)
        self.studienummerLabel.setObjectName("studienummerLabel")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.studienummerLabel)
        self.studentId_fld = QtWidgets.QLineEdit(MemberEdit)
        self.studentId_fld.setObjectName("studentId_fld")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.studentId_fld)
        self.avlidenLabel = QtWidgets.QLabel(MemberEdit)
        self.avlidenLabel.setObjectName("avlidenLabel")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.avlidenLabel)
        self.dead_fld = QtWidgets.QCheckBox(MemberEdit)
        self.dead_fld.setObjectName("dead_fld")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.dead_fld)
        self.fDelsedatumLabel = QtWidgets.QLabel(MemberEdit)
        self.fDelsedatumLabel.setObjectName("fDelsedatumLabel")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.fDelsedatumLabel)
        self.birthDate_fld = QtWidgets.QDateEdit(MemberEdit)
        self.birthDate_fld.setCalendarPopup(True)
        self.birthDate_fld.setObjectName("birthDate_fld")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.birthDate_fld)
        self.nationalitetLabel = QtWidgets.QLabel(MemberEdit)
        self.nationalitetLabel.setObjectName("nationalitetLabel")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.nationalitetLabel)
        self.nationality_fld = QtWidgets.QLineEdit(MemberEdit)
        self.nationality_fld.setObjectName("nationality_fld")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.nationality_fld)
        self.kNLabel = QtWidgets.QLabel(MemberEdit)
        self.kNLabel.setObjectName("kNLabel")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.kNLabel)
        self.gender_fld = QtWidgets.QComboBox(MemberEdit)
        self.gender_fld.setObjectName("gender_fld")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.gender_fld)
        self.subscribedToModulen_fld = QtWidgets.QLabel(MemberEdit)
        self.subscribedToModulen_fld.setObjectName("subscribedToModulen_fld")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.subscribedToModulen_fld)
        self.subscribedToModulen_fld_checkbox = QtWidgets.QCheckBox(MemberEdit)
        self.subscribedToModulen_fld_checkbox.setObjectName("subscribedToModulen_fld_checkbox")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.subscribedToModulen_fld_checkbox)
        self.username_fldLabel = QtWidgets.QLabel(MemberEdit)
        self.username_fldLabel.setObjectName("username_fldLabel")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.username_fldLabel)
        self.username_fld = QtWidgets.QLineEdit(MemberEdit)
        self.username_fld.setObjectName("username_fld")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.username_fld)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.notes_fldLabel = QtWidgets.QLabel(MemberEdit)
        self.notes_fldLabel.setObjectName("notes_fldLabel")
        self.verticalLayout.addWidget(self.notes_fldLabel)
        self.notes_fld = QtWidgets.QPlainTextEdit(MemberEdit)
        self.notes_fld.setObjectName("notes_fld")
        self.verticalLayout.addWidget(self.notes_fld)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.gatuadressLabel = QtWidgets.QLabel(MemberEdit)
        self.gatuadressLabel.setObjectName("gatuadressLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.gatuadressLabel)
        self.streetAddress_fld = QtWidgets.QLineEdit(MemberEdit)
        self.streetAddress_fld.setObjectName("streetAddress_fld")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.streetAddress_fld)
        self.postnummerLabel = QtWidgets.QLabel(MemberEdit)
        self.postnummerLabel.setObjectName("postnummerLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.postnummerLabel)
        self.postalCode_fld = QtWidgets.QLineEdit(MemberEdit)
        self.postalCode_fld.setObjectName("postalCode_fld")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.postalCode_fld)
        self.stadLabel = QtWidgets.QLabel(MemberEdit)
        self.stadLabel.setObjectName("stadLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.stadLabel)
        self.city_fld = QtWidgets.QLineEdit(MemberEdit)
        self.city_fld.setObjectName("city_fld")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.city_fld)
        self.landLabel = QtWidgets.QLabel(MemberEdit)
        self.landLabel.setObjectName("landLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.landLabel)
        self.country_fld = QtWidgets.QLineEdit(MemberEdit)
        self.country_fld.setObjectName("country_fld")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.country_fld)
        self.telefonLabel = QtWidgets.QLabel(MemberEdit)
        self.telefonLabel.setObjectName("telefonLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.telefonLabel)
        self.phone_fld = QtWidgets.QLineEdit(MemberEdit)
        self.phone_fld.setObjectName("phone_fld")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.phone_fld)
        self.emailLabel = QtWidgets.QLabel(MemberEdit)
        self.emailLabel.setObjectName("emailLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.emailLabel)
        self.email_fld = QtWidgets.QLineEdit(MemberEdit)
        self.email_fld.setObjectName("email_fld")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.email_fld)
        self.lbl_noPublishing = QtWidgets.QLabel(MemberEdit)
        self.lbl_noPublishing.setObjectName("lbl_noPublishing")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.lbl_noPublishing)
        self.noPublishContactInfo_fld_checkbox = QtWidgets.QCheckBox(MemberEdit)
        self.noPublishContactInfo_fld_checkbox.setObjectName("noPublishContactInfo_fld_checkbox")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.noPublishContactInfo_fld_checkbox)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.tabWidget = QtWidgets.QTabWidget(MemberEdit)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.groupView = QtWidgets.QListView(self.tab)
        self.groupView.setObjectName("groupView")
        self.horizontalLayout_7.addWidget(self.groupView)
        self.removeGroupButton = QtWidgets.QPushButton(self.tab)
        self.removeGroupButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/res/list_remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.removeGroupButton.setIcon(icon)
        self.removeGroupButton.setObjectName("removeGroupButton")
        self.horizontalLayout_7.addWidget(self.removeGroupButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.group_comboBox = QtWidgets.QComboBox(self.tab)
        self.group_comboBox.setEditable(True)
        self.group_comboBox.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.group_comboBox.setObjectName("group_comboBox")
        self.horizontalLayout_2.addWidget(self.group_comboBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.postView = QtWidgets.QListView(self.tab)
        self.postView.setObjectName("postView")
        self.horizontalLayout_8.addWidget(self.postView)
        self.removePostButton = QtWidgets.QPushButton(self.tab)
        self.removePostButton.setText("")
        self.removePostButton.setIcon(icon)
        self.removePostButton.setObjectName("removePostButton")
        self.horizontalLayout_8.addWidget(self.removePostButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.post_comboBox = QtWidgets.QComboBox(self.tab)
        self.post_comboBox.setEditable(True)
        self.post_comboBox.setObjectName("post_comboBox")
        self.horizontalLayout_3.addWidget(self.post_comboBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.tab, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.billAccountStatusLabel = QtWidgets.QLabel(self.tab_6)
        self.billAccountStatusLabel.setObjectName("billAccountStatusLabel")
        self.gridLayout_2.addWidget(self.billAccountStatusLabel, 1, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.tab_6)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 0, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.tab_6)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 2, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.tab_6)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 1, 0, 1, 1)
        self.billAccountCreditLabel = QtWidgets.QLabel(self.tab_6)
        self.billAccountCreditLabel.setObjectName("billAccountCreditLabel")
        self.gridLayout_2.addWidget(self.billAccountCreditLabel, 2, 1, 1, 1)
        self.ldapAccountStatusLabel = QtWidgets.QLabel(self.tab_6)
        self.ldapAccountStatusLabel.setObjectName("ldapAccountStatusLabel")
        self.gridLayout_2.addWidget(self.ldapAccountStatusLabel, 0, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.tab_6)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 3, 0, 1, 1)
        self.ldapGroupsLabel = QtWidgets.QPlainTextEdit(self.tab_6)
        self.ldapGroupsLabel.setEnabled(True)
        self.ldapGroupsLabel.setReadOnly(True)
        self.ldapGroupsLabel.setPlainText("")
        self.ldapGroupsLabel.setBackgroundVisible(False)
        self.ldapGroupsLabel.setObjectName("ldapGroupsLabel")
        self.gridLayout_2.addWidget(self.ldapGroupsLabel, 3, 1, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_2)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.createUserAccountOrChangePasswordButton = QtWidgets.QPushButton(self.tab_6)
        self.createUserAccountOrChangePasswordButton.setObjectName("createUserAccountOrChangePasswordButton")
        self.verticalLayout_7.addWidget(self.createUserAccountOrChangePasswordButton)
        self.removeAccountButton = QtWidgets.QPushButton(self.tab_6)
        self.removeAccountButton.setObjectName("removeAccountButton")
        self.verticalLayout_7.addWidget(self.removeAccountButton)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_5.addWidget(self.label_10)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.departmentView = QtWidgets.QListView(self.tab_2)
        self.departmentView.setObjectName("departmentView")
        self.horizontalLayout_12.addWidget(self.departmentView)
        self.removeDepartmentButton = QtWidgets.QPushButton(self.tab_2)
        self.removeDepartmentButton.setText("")
        self.removeDepartmentButton.setIcon(icon)
        self.removeDepartmentButton.setObjectName("removeDepartmentButton")
        self.horizontalLayout_12.addWidget(self.removeDepartmentButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        self.department_comboBox = QtWidgets.QComboBox(self.tab_2)
        self.department_comboBox.setEditable(True)
        self.department_comboBox.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.department_comboBox.setObjectName("department_comboBox")
        self.horizontalLayout_6.addWidget(self.department_comboBox)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.label_12 = QtWidgets.QLabel(self.tab_2)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_5.addWidget(self.label_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.membershipView = QtWidgets.QListView(self.tab_2)
        self.membershipView.setObjectName("membershipView")
        self.horizontalLayout_13.addWidget(self.membershipView)
        self.removeMembershipButton = QtWidgets.QPushButton(self.tab_2)
        self.removeMembershipButton.setText("")
        self.removeMembershipButton.setIcon(icon)
        self.removeMembershipButton.setObjectName("removeMembershipButton")
        self.horizontalLayout_13.addWidget(self.removeMembershipButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.makePhuxButton = QtWidgets.QPushButton(self.tab_2)
        self.makePhuxButton.setObjectName("makePhuxButton")
        self.horizontalLayout_14.addWidget(self.makePhuxButton)
        self.makeOrdinarieButton = QtWidgets.QPushButton(self.tab_2)
        self.makeOrdinarieButton.setObjectName("makeOrdinarieButton")
        self.horizontalLayout_14.addWidget(self.makeOrdinarieButton)
        self.makeEjMedlemButton = QtWidgets.QPushButton(self.tab_2)
        self.makeEjMedlemButton.setObjectName("makeEjMedlemButton")
        self.horizontalLayout_14.addWidget(self.makeEjMedlemButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.makeActiveAlumnButton = QtWidgets.QPushButton(self.tab_2)
        self.makeActiveAlumnButton.setObjectName("makeActiveAlumnButton")
        self.horizontalLayout_4.addWidget(self.makeActiveAlumnButton)
        self.makeStAlMButton = QtWidgets.QPushButton(self.tab_2)
        self.makeStAlMButton.setObjectName("makeStAlMButton")
        self.horizontalLayout_4.addWidget(self.makeStAlMButton)
        self.makeJuniorStAlMButton = QtWidgets.QPushButton(self.tab_2)
        self.makeJuniorStAlMButton.setObjectName("makeJuniorStAlMButton")
        self.horizontalLayout_4.addWidget(self.makeJuniorStAlMButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_9.addWidget(self.label_11)
        self.membership_comboBox = QtWidgets.QComboBox(self.tab_2)
        self.membership_comboBox.setEditable(True)
        self.membership_comboBox.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.membership_comboBox.setObjectName("membership_comboBox")
        self.horizontalLayout_9.addWidget(self.membership_comboBox)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(MemberEdit)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.allaFornamnLabel.setBuddy(self.givenNames_fld)
        self.efternamnLabel.setBuddy(self.surName_fld)
        self.tidigareEfternamnLabel.setBuddy(self.maidenName_fld)
        self.tilltalsnamnLabel.setBuddy(self.preferredName_fld)
        self.studienummerLabel.setBuddy(self.studentId_fld)
        self.avlidenLabel.setBuddy(self.dead_fld)
        self.fDelsedatumLabel.setBuddy(self.birthDate_fld)
        self.nationalitetLabel.setBuddy(self.nationality_fld)
        self.kNLabel.setBuddy(self.gender_fld)
        self.subscribedToModulen_fld.setBuddy(self.subscribedToModulen_fld_checkbox)
        self.username_fldLabel.setBuddy(self.username_fld)
        self.notes_fldLabel.setBuddy(self.notes_fld)
        self.gatuadressLabel.setBuddy(self.streetAddress_fld)
        self.postnummerLabel.setBuddy(self.postalCode_fld)
        self.stadLabel.setBuddy(self.city_fld)
        self.landLabel.setBuddy(self.country_fld)
        self.telefonLabel.setBuddy(self.phone_fld)
        self.emailLabel.setBuddy(self.email_fld)
        self.label_3.setBuddy(self.group_comboBox)
        self.label_4.setBuddy(self.post_comboBox)
        self.label_9.setBuddy(self.group_comboBox)
        self.label_11.setBuddy(self.group_comboBox)

        self.retranslateUi(MemberEdit)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(MemberEdit.accept)
        self.buttonBox.rejected.connect(MemberEdit.reject)
        QtCore.QMetaObject.connectSlotsByName(MemberEdit)
        MemberEdit.setTabOrder(self.givenNames_fld, self.surName_fld)
        MemberEdit.setTabOrder(self.surName_fld, self.maidenName_fld)
        MemberEdit.setTabOrder(self.maidenName_fld, self.preferredName_fld)
        MemberEdit.setTabOrder(self.preferredName_fld, self.studentId_fld)
        MemberEdit.setTabOrder(self.studentId_fld, self.dead_fld)
        MemberEdit.setTabOrder(self.dead_fld, self.birthDate_fld)
        MemberEdit.setTabOrder(self.birthDate_fld, self.nationality_fld)
        MemberEdit.setTabOrder(self.nationality_fld, self.gender_fld)
        MemberEdit.setTabOrder(self.gender_fld, self.subscribedToModulen_fld_checkbox)
        MemberEdit.setTabOrder(self.subscribedToModulen_fld_checkbox, self.username_fld)
        MemberEdit.setTabOrder(self.username_fld, self.notes_fld)
        MemberEdit.setTabOrder(self.notes_fld, self.buttonBox)
        MemberEdit.setTabOrder(self.buttonBox, self.streetAddress_fld)
        MemberEdit.setTabOrder(self.streetAddress_fld, self.postalCode_fld)
        MemberEdit.setTabOrder(self.postalCode_fld, self.city_fld)
        MemberEdit.setTabOrder(self.city_fld, self.country_fld)
        MemberEdit.setTabOrder(self.country_fld, self.phone_fld)
        MemberEdit.setTabOrder(self.phone_fld, self.email_fld)
        MemberEdit.setTabOrder(self.email_fld, self.groupView)
        MemberEdit.setTabOrder(self.groupView, self.removeGroupButton)
        MemberEdit.setTabOrder(self.removeGroupButton, self.group_comboBox)
        MemberEdit.setTabOrder(self.group_comboBox, self.postView)
        MemberEdit.setTabOrder(self.postView, self.removePostButton)
        MemberEdit.setTabOrder(self.removePostButton, self.post_comboBox)

    def retranslateUi(self, MemberEdit):
        _translate = QtCore.QCoreApplication.translate
        MemberEdit.setWindowTitle(_translate("MemberEdit", "Dialog"))
        self.allaFornamnLabel.setText(_translate("MemberEdit", "Alla förnamn"))
        self.efternamnLabel.setText(_translate("MemberEdit", "Efternamn"))
        self.tidigareEfternamnLabel.setText(_translate("MemberEdit", "Tidigare efternamn"))
        self.tilltalsnamnLabel.setText(_translate("MemberEdit", "Tilltalsnamn"))
        self.studienummerLabel.setText(_translate("MemberEdit", "Studienummer"))
        self.avlidenLabel.setText(_translate("MemberEdit", "Avliden"))
        self.fDelsedatumLabel.setText(_translate("MemberEdit", "Födelsedatum"))
        self.nationalitetLabel.setText(_translate("MemberEdit", "Nationalitet"))
        self.kNLabel.setText(_translate("MemberEdit", "Kön"))
        self.subscribedToModulen_fld.setText(_translate("MemberEdit", "Vill ha Modulen"))
        self.username_fldLabel.setText(_translate("MemberEdit", "Användarnamn"))
        self.notes_fldLabel.setText(_translate("MemberEdit", "Kommentarer (Max 255 st. tecken)"))
        self.gatuadressLabel.setText(_translate("MemberEdit", "Gatuadress"))
        self.postnummerLabel.setText(_translate("MemberEdit", "Postnummer"))
        self.stadLabel.setText(_translate("MemberEdit", "Stad"))
        self.landLabel.setText(_translate("MemberEdit", "Land"))
        self.telefonLabel.setText(_translate("MemberEdit", "Telefon"))
        self.emailLabel.setText(_translate("MemberEdit", "Email"))
        self.lbl_noPublishing.setText(_translate("MemberEdit", "Publicera INTE addressuppgifter"))
        self.label.setText(_translate("MemberEdit", "Grupper:"))
        self.label_3.setText(_translate("MemberEdit", "Lägg till grupp:"))
        self.label_2.setText(_translate("MemberEdit", "Poster:"))
        self.label_4.setText(_translate("MemberEdit", "Lägg till post:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MemberEdit", "TF-Aktivitet"))
        self.billAccountStatusLabel.setText(_translate("MemberEdit", "TextLabel"))
        self.label_18.setText(_translate("MemberEdit", "LDAP-konto"))
        self.label_19.setText(_translate("MemberEdit", "BILL-kredit"))
        self.label_20.setText(_translate("MemberEdit", "BILL-konto"))
        self.billAccountCreditLabel.setText(_translate("MemberEdit", "TextLabel"))
        self.ldapAccountStatusLabel.setText(_translate("MemberEdit", "TextLabel"))
        self.label_21.setText(_translate("MemberEdit", "LDAP-Grupper"))
        self.createUserAccountOrChangePasswordButton.setText(_translate("MemberEdit", "Skapa användarkonton/Byt lösenord"))
        self.removeAccountButton.setText(_translate("MemberEdit", "Ta bort användarkonto"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MemberEdit", "Användarkonton"))
        self.label_10.setText(_translate("MemberEdit", "Studieinriktning:"))
        self.label_9.setText(_translate("MemberEdit", "Lägg till studieinriktning:"))
        self.label_12.setText(_translate("MemberEdit", "TF Medlemskapstyper:"))
        self.makePhuxButton.setText(_translate("MemberEdit", "Phux"))
        self.makeOrdinarieButton.setText(_translate("MemberEdit", "Ordinarie"))
        self.makeEjMedlemButton.setText(_translate("MemberEdit", "Ej medlem"))
        self.makeActiveAlumnButton.setText(_translate("MemberEdit", "Aktiv alumn"))
        self.makeStAlMButton.setText(_translate("MemberEdit", "StÄlM"))
        self.makeJuniorStAlMButton.setText(_translate("MemberEdit", "JuniorStÄlM"))
        self.label_11.setText(_translate("MemberEdit", "Lägg till medlemskapstyp:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MemberEdit", "Aalto och TF medlemskap"))

import svaksvat_rc
