# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newmember.ui'
#
# Created: Sat Mar 29 19:36:48 2014
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_NewMember(object):
    def setupUi(self, NewMember):
        NewMember.setObjectName("NewMember")
        NewMember.resize(370, 540)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(NewMember)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.efternamnLabel = QtWidgets.QLabel(NewMember)
        self.efternamnLabel.setObjectName("efternamnLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.efternamnLabel)
        self.surName_fld = QtWidgets.QLineEdit(NewMember)
        self.surName_fld.setObjectName("surName_fld")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.surName_fld)
        self.allaFRnamnLabel = QtWidgets.QLabel(NewMember)
        self.allaFRnamnLabel.setObjectName("allaFRnamnLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.allaFRnamnLabel)
        self.givenNames_fld = QtWidgets.QLineEdit(NewMember)
        self.givenNames_fld.setObjectName("givenNames_fld")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.givenNames_fld)
        self.tilltalsnamnLabel = QtWidgets.QLabel(NewMember)
        self.tilltalsnamnLabel.setObjectName("tilltalsnamnLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.tilltalsnamnLabel)
        self.preferredName_fld = QtWidgets.QLineEdit(NewMember)
        self.preferredName_fld.setObjectName("preferredName_fld")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.preferredName_fld)
        self.kNLabel = QtWidgets.QLabel(NewMember)
        self.kNLabel.setObjectName("kNLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.kNLabel)
        self.gender_fld = QtWidgets.QComboBox(NewMember)
        self.gender_fld.setObjectName("gender_fld")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.gender_fld)
        self.birthDateLabel = QtWidgets.QLabel(NewMember)
        self.birthDateLabel.setObjectName("birthDateLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.birthDateLabel)
        self.birthDate_fld = QtWidgets.QDateEdit(NewMember)
        self.birthDate_fld.setObjectName("birthDate_fld")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.birthDate_fld)
        self.adressLabel = QtWidgets.QLabel(NewMember)
        self.adressLabel.setObjectName("adressLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.adressLabel)
        self.streetAddress_fld = QtWidgets.QLineEdit(NewMember)
        self.streetAddress_fld.setObjectName("streetAddress_fld")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.streetAddress_fld)
        self.postnummerLabel = QtWidgets.QLabel(NewMember)
        self.postnummerLabel.setObjectName("postnummerLabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.postnummerLabel)
        self.postalCode_fld = QtWidgets.QLineEdit(NewMember)
        self.postalCode_fld.setObjectName("postalCode_fld")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.postalCode_fld)
        self.postanstaltLabel = QtWidgets.QLabel(NewMember)
        self.postanstaltLabel.setObjectName("postanstaltLabel")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.postanstaltLabel)
        self.city_fld = QtWidgets.QLineEdit(NewMember)
        self.city_fld.setObjectName("city_fld")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.city_fld)
        self.telefonLabel = QtWidgets.QLabel(NewMember)
        self.telefonLabel.setObjectName("telefonLabel")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.telefonLabel)
        self.phone_fld = QtWidgets.QLineEdit(NewMember)
        self.phone_fld.setObjectName("phone_fld")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.phone_fld)
        self.emailLabel = QtWidgets.QLabel(NewMember)
        self.emailLabel.setObjectName("emailLabel")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.emailLabel)
        self.email_fld = QtWidgets.QLineEdit(NewMember)
        self.email_fld.setObjectName("email_fld")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.email_fld)
        self.avdelningLabel = QtWidgets.QLabel(NewMember)
        self.avdelningLabel.setObjectName("avdelningLabel")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.avdelningLabel)
        self.department_comboBox = QtWidgets.QComboBox(NewMember)
        self.department_comboBox.setEditable(True)
        self.department_comboBox.setObjectName("department_comboBox")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.department_comboBox)
        self.anvNdarnamnLabel = QtWidgets.QLabel(NewMember)
        self.anvNdarnamnLabel.setObjectName("anvNdarnamnLabel")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.anvNdarnamnLabel)
        self.username_fld = QtWidgets.QLineEdit(NewMember)
        self.username_fld.setObjectName("username_fld")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.username_fld)
        self.gRTillPhuxLabel = QtWidgets.QLabel(NewMember)
        self.gRTillPhuxLabel.setObjectName("gRTillPhuxLabel")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.gRTillPhuxLabel)
        self.makePhux_CheckBox = QtWidgets.QCheckBox(NewMember)
        self.makePhux_CheckBox.setObjectName("makePhux_CheckBox")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.makePhux_CheckBox)
        self.studentId_label = QtWidgets.QLabel(NewMember)
        self.studentId_label.setObjectName("studentId_label")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.studentId_label)
        self.studentId_fld = QtWidgets.QLineEdit(NewMember)
        self.studentId_fld.setObjectName("studentId_fld")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.studentId_fld)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(NewMember)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(NewMember)
        self.buttonBox.accepted.connect(NewMember.accept)
        self.buttonBox.rejected.connect(NewMember.reject)
        QtCore.QMetaObject.connectSlotsByName(NewMember)
        NewMember.setTabOrder(self.surName_fld, self.givenNames_fld)
        NewMember.setTabOrder(self.givenNames_fld, self.preferredName_fld)
        NewMember.setTabOrder(self.preferredName_fld, self.gender_fld)
        NewMember.setTabOrder(self.gender_fld, self.birthDate_fld)
        NewMember.setTabOrder(self.birthDate_fld, self.streetAddress_fld)
        NewMember.setTabOrder(self.streetAddress_fld, self.postalCode_fld)
        NewMember.setTabOrder(self.postalCode_fld, self.city_fld)
        NewMember.setTabOrder(self.city_fld, self.phone_fld)
        NewMember.setTabOrder(self.phone_fld, self.email_fld)
        NewMember.setTabOrder(self.email_fld, self.department_comboBox)
        NewMember.setTabOrder(self.department_comboBox, self.studentId_fld)
        NewMember.setTabOrder(self.studentId_fld, self.username_fld)
        NewMember.setTabOrder(self.username_fld, self.makePhux_CheckBox)
        NewMember.setTabOrder(self.makePhux_CheckBox, self.buttonBox)

    def retranslateUi(self, NewMember):
        _translate = QtCore.QCoreApplication.translate
        NewMember.setWindowTitle(_translate("NewMember", "Dialog"))
        self.efternamnLabel.setText(_translate("NewMember", "Efternamn"))
        self.allaFRnamnLabel.setText(_translate("NewMember", "Alla förnamn"))
        self.tilltalsnamnLabel.setText(_translate("NewMember", "Tilltalsnamn"))
        self.kNLabel.setText(_translate("NewMember", "Kön"))
        self.birthDateLabel.setText(_translate("NewMember", "Födelsedatum"))
        self.adressLabel.setText(_translate("NewMember", "Gatuadress"))
        self.postnummerLabel.setText(_translate("NewMember", "Postnummer"))
        self.postanstaltLabel.setText(_translate("NewMember", "Postanstalt"))
        self.telefonLabel.setText(_translate("NewMember", "Telefon"))
        self.emailLabel.setText(_translate("NewMember", "Email"))
        self.avdelningLabel.setText(_translate("NewMember", "Avdelning"))
        self.anvNdarnamnLabel.setText(_translate("NewMember", "Användarnamn"))
        self.gRTillPhuxLabel.setText(_translate("NewMember", "Gör till Phux"))
        self.studentId_label.setText(_translate("NewMember", "Studienummer"))

