# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newmember.ui'
#
# Created: Sat Sep  1 18:50:46 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_NewMember(object):
    def setupUi(self, NewMember):
        NewMember.setObjectName(_fromUtf8("NewMember"))
        NewMember.resize(370, 439)
        self.verticalLayout_2 = QtGui.QVBoxLayout(NewMember)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.efternamnLabel = QtGui.QLabel(NewMember)
        self.efternamnLabel.setObjectName(_fromUtf8("efternamnLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.efternamnLabel)
        self.surName_fld = QtGui.QLineEdit(NewMember)
        self.surName_fld.setObjectName(_fromUtf8("surName_fld"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.surName_fld)
        self.allaFRnamnLabel = QtGui.QLabel(NewMember)
        self.allaFRnamnLabel.setObjectName(_fromUtf8("allaFRnamnLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.allaFRnamnLabel)
        self.givenNames_fld = QtGui.QLineEdit(NewMember)
        self.givenNames_fld.setObjectName(_fromUtf8("givenNames_fld"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.givenNames_fld)
        self.tilltalsnamnLabel = QtGui.QLabel(NewMember)
        self.tilltalsnamnLabel.setObjectName(_fromUtf8("tilltalsnamnLabel"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.tilltalsnamnLabel)
        self.preferredName_fld = QtGui.QLineEdit(NewMember)
        self.preferredName_fld.setObjectName(_fromUtf8("preferredName_fld"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.preferredName_fld)
        self.adressLabel = QtGui.QLabel(NewMember)
        self.adressLabel.setObjectName(_fromUtf8("adressLabel"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.adressLabel)
        self.streetAddress_fld = QtGui.QLineEdit(NewMember)
        self.streetAddress_fld.setObjectName(_fromUtf8("streetAddress_fld"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.streetAddress_fld)
        self.telefonLabel = QtGui.QLabel(NewMember)
        self.telefonLabel.setObjectName(_fromUtf8("telefonLabel"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.telefonLabel)
        self.phone_fld = QtGui.QLineEdit(NewMember)
        self.phone_fld.setObjectName(_fromUtf8("phone_fld"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.phone_fld)
        self.emailLabel = QtGui.QLabel(NewMember)
        self.emailLabel.setObjectName(_fromUtf8("emailLabel"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.emailLabel)
        self.email_fld = QtGui.QLineEdit(NewMember)
        self.email_fld.setObjectName(_fromUtf8("email_fld"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.email_fld)
        self.avdelningLabel = QtGui.QLabel(NewMember)
        self.avdelningLabel.setObjectName(_fromUtf8("avdelningLabel"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.avdelningLabel)
        self.department_comboBox = QtGui.QComboBox(NewMember)
        self.department_comboBox.setEditable(True)
        self.department_comboBox.setObjectName(_fromUtf8("department_comboBox"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.department_comboBox)
        self.anvNdarnamnLabel = QtGui.QLabel(NewMember)
        self.anvNdarnamnLabel.setObjectName(_fromUtf8("anvNdarnamnLabel"))
        self.formLayout.setWidget(10, QtGui.QFormLayout.LabelRole, self.anvNdarnamnLabel)
        self.username_fld = QtGui.QLineEdit(NewMember)
        self.username_fld.setObjectName(_fromUtf8("username_fld"))
        self.formLayout.setWidget(10, QtGui.QFormLayout.FieldRole, self.username_fld)
        self.gRTillPhuxLabel = QtGui.QLabel(NewMember)
        self.gRTillPhuxLabel.setObjectName(_fromUtf8("gRTillPhuxLabel"))
        self.formLayout.setWidget(11, QtGui.QFormLayout.LabelRole, self.gRTillPhuxLabel)
        self.makePhux_CheckBox = QtGui.QCheckBox(NewMember)
        self.makePhux_CheckBox.setObjectName(_fromUtf8("makePhux_CheckBox"))
        self.formLayout.setWidget(11, QtGui.QFormLayout.FieldRole, self.makePhux_CheckBox)
        self.kNLabel = QtGui.QLabel(NewMember)
        self.kNLabel.setObjectName(_fromUtf8("kNLabel"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.kNLabel)
        self.gender_fld = QtGui.QComboBox(NewMember)
        self.gender_fld.setObjectName(_fromUtf8("gender_fld"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.gender_fld)
        self.postnummerLabel = QtGui.QLabel(NewMember)
        self.postnummerLabel.setObjectName(_fromUtf8("postnummerLabel"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.postnummerLabel)
        self.postalCode_fld = QtGui.QLineEdit(NewMember)
        self.postalCode_fld.setObjectName(_fromUtf8("postalCode_fld"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.postalCode_fld)
        self.postanstaltLabel = QtGui.QLabel(NewMember)
        self.postanstaltLabel.setObjectName(_fromUtf8("postanstaltLabel"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.postanstaltLabel)
        self.city_fld = QtGui.QLineEdit(NewMember)
        self.city_fld.setObjectName(_fromUtf8("city_fld"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.city_fld)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtGui.QDialogButtonBox(NewMember)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(NewMember)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), NewMember.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), NewMember.reject)
        QtCore.QMetaObject.connectSlotsByName(NewMember)
        NewMember.setTabOrder(self.surName_fld, self.givenNames_fld)
        NewMember.setTabOrder(self.givenNames_fld, self.preferredName_fld)
        NewMember.setTabOrder(self.preferredName_fld, self.gender_fld)
        NewMember.setTabOrder(self.gender_fld, self.streetAddress_fld)
        NewMember.setTabOrder(self.streetAddress_fld, self.postalCode_fld)
        NewMember.setTabOrder(self.postalCode_fld, self.city_fld)
        NewMember.setTabOrder(self.city_fld, self.phone_fld)
        NewMember.setTabOrder(self.phone_fld, self.email_fld)
        NewMember.setTabOrder(self.email_fld, self.department_comboBox)
        NewMember.setTabOrder(self.department_comboBox, self.username_fld)
        NewMember.setTabOrder(self.username_fld, self.makePhux_CheckBox)
        NewMember.setTabOrder(self.makePhux_CheckBox, self.buttonBox)

    def retranslateUi(self, NewMember):
        NewMember.setWindowTitle(QtGui.QApplication.translate("NewMember", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.efternamnLabel.setText(QtGui.QApplication.translate("NewMember", "Efternamn", None, QtGui.QApplication.UnicodeUTF8))
        self.allaFRnamnLabel.setText(QtGui.QApplication.translate("NewMember", "Alla förnamn", None, QtGui.QApplication.UnicodeUTF8))
        self.tilltalsnamnLabel.setText(QtGui.QApplication.translate("NewMember", "Tilltalsnamn", None, QtGui.QApplication.UnicodeUTF8))
        self.adressLabel.setText(QtGui.QApplication.translate("NewMember", "Gatuadress", None, QtGui.QApplication.UnicodeUTF8))
        self.telefonLabel.setText(QtGui.QApplication.translate("NewMember", "Telefon", None, QtGui.QApplication.UnicodeUTF8))
        self.emailLabel.setText(QtGui.QApplication.translate("NewMember", "Email", None, QtGui.QApplication.UnicodeUTF8))
        self.avdelningLabel.setText(QtGui.QApplication.translate("NewMember", "Avdelning", None, QtGui.QApplication.UnicodeUTF8))
        self.anvNdarnamnLabel.setText(QtGui.QApplication.translate("NewMember", "Användarnamn", None, QtGui.QApplication.UnicodeUTF8))
        self.gRTillPhuxLabel.setText(QtGui.QApplication.translate("NewMember", "Gör till Phux", None, QtGui.QApplication.UnicodeUTF8))
        self.kNLabel.setText(QtGui.QApplication.translate("NewMember", "Kön", None, QtGui.QApplication.UnicodeUTF8))
        self.postnummerLabel.setText(QtGui.QApplication.translate("NewMember", "Postnummer", None, QtGui.QApplication.UnicodeUTF8))
        self.postanstaltLabel.setText(QtGui.QApplication.translate("NewMember", "Postanstalt", None, QtGui.QApplication.UnicodeUTF8))

