# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/newmember.ui'
#
# Created: Wed Sep 11 09:54:50 2013
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_NewMember(object):
    def setupUi(self, NewMember):
        NewMember.setObjectName(_fromUtf8("NewMember"))
        NewMember.resize(370, 540)
        self.verticalLayout_2 = QtGui.QVBoxLayout(NewMember)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.efternamnLabel = QtGui.QLabel(NewMember)
        self.efternamnLabel.setObjectName(_fromUtf8("efternamnLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.efternamnLabel)
        self.surName_fld = QtGui.QLineEdit(NewMember)
        self.surName_fld.setObjectName(_fromUtf8("surName_fld"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.surName_fld)
        self.allaFRnamnLabel = QtGui.QLabel(NewMember)
        self.allaFRnamnLabel.setObjectName(_fromUtf8("allaFRnamnLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.allaFRnamnLabel)
        self.givenNames_fld = QtGui.QLineEdit(NewMember)
        self.givenNames_fld.setObjectName(_fromUtf8("givenNames_fld"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.givenNames_fld)
        self.tilltalsnamnLabel = QtGui.QLabel(NewMember)
        self.tilltalsnamnLabel.setObjectName(_fromUtf8("tilltalsnamnLabel"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.tilltalsnamnLabel)
        self.preferredName_fld = QtGui.QLineEdit(NewMember)
        self.preferredName_fld.setObjectName(_fromUtf8("preferredName_fld"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.preferredName_fld)
        self.kNLabel = QtGui.QLabel(NewMember)
        self.kNLabel.setObjectName(_fromUtf8("kNLabel"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.kNLabel)
        self.gender_fld = QtGui.QComboBox(NewMember)
        self.gender_fld.setObjectName(_fromUtf8("gender_fld"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.gender_fld)
        self.birthDateLabel = QtGui.QLabel(NewMember)
        self.birthDateLabel.setObjectName(_fromUtf8("birthDateLabel"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.birthDateLabel)
        self.birthDate_fld = QtGui.QDateEdit(NewMember)
        self.birthDate_fld.setObjectName(_fromUtf8("birthDate_fld"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.birthDate_fld)
        self.adressLabel = QtGui.QLabel(NewMember)
        self.adressLabel.setObjectName(_fromUtf8("adressLabel"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.adressLabel)
        self.streetAddress_fld = QtGui.QLineEdit(NewMember)
        self.streetAddress_fld.setObjectName(_fromUtf8("streetAddress_fld"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.streetAddress_fld)
        self.postnummerLabel = QtGui.QLabel(NewMember)
        self.postnummerLabel.setObjectName(_fromUtf8("postnummerLabel"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.postnummerLabel)
        self.postalCode_fld = QtGui.QLineEdit(NewMember)
        self.postalCode_fld.setObjectName(_fromUtf8("postalCode_fld"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.postalCode_fld)
        self.postanstaltLabel = QtGui.QLabel(NewMember)
        self.postanstaltLabel.setObjectName(_fromUtf8("postanstaltLabel"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.postanstaltLabel)
        self.city_fld = QtGui.QLineEdit(NewMember)
        self.city_fld.setObjectName(_fromUtf8("city_fld"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.city_fld)
        self.telefonLabel = QtGui.QLabel(NewMember)
        self.telefonLabel.setObjectName(_fromUtf8("telefonLabel"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.telefonLabel)
        self.phone_fld = QtGui.QLineEdit(NewMember)
        self.phone_fld.setObjectName(_fromUtf8("phone_fld"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.phone_fld)
        self.emailLabel = QtGui.QLabel(NewMember)
        self.emailLabel.setObjectName(_fromUtf8("emailLabel"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.emailLabel)
        self.email_fld = QtGui.QLineEdit(NewMember)
        self.email_fld.setObjectName(_fromUtf8("email_fld"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.email_fld)
        self.avdelningLabel = QtGui.QLabel(NewMember)
        self.avdelningLabel.setObjectName(_fromUtf8("avdelningLabel"))
        self.formLayout.setWidget(10, QtGui.QFormLayout.LabelRole, self.avdelningLabel)
        self.department_comboBox = QtGui.QComboBox(NewMember)
        self.department_comboBox.setEditable(True)
        self.department_comboBox.setObjectName(_fromUtf8("department_comboBox"))
        self.formLayout.setWidget(10, QtGui.QFormLayout.FieldRole, self.department_comboBox)
        self.anvNdarnamnLabel = QtGui.QLabel(NewMember)
        self.anvNdarnamnLabel.setObjectName(_fromUtf8("anvNdarnamnLabel"))
        self.formLayout.setWidget(12, QtGui.QFormLayout.LabelRole, self.anvNdarnamnLabel)
        self.username_fld = QtGui.QLineEdit(NewMember)
        self.username_fld.setObjectName(_fromUtf8("username_fld"))
        self.formLayout.setWidget(12, QtGui.QFormLayout.FieldRole, self.username_fld)
        self.gRTillPhuxLabel = QtGui.QLabel(NewMember)
        self.gRTillPhuxLabel.setObjectName(_fromUtf8("gRTillPhuxLabel"))
        self.formLayout.setWidget(13, QtGui.QFormLayout.LabelRole, self.gRTillPhuxLabel)
        self.makePhux_CheckBox = QtGui.QCheckBox(NewMember)
        self.makePhux_CheckBox.setObjectName(_fromUtf8("makePhux_CheckBox"))
        self.formLayout.setWidget(13, QtGui.QFormLayout.FieldRole, self.makePhux_CheckBox)
        self.studentId_label = QtGui.QLabel(NewMember)
        self.studentId_label.setObjectName(_fromUtf8("studentId_label"))
        self.formLayout.setWidget(11, QtGui.QFormLayout.LabelRole, self.studentId_label)
        self.studentId_fld = QtGui.QLineEdit(NewMember)
        self.studentId_fld.setObjectName(_fromUtf8("studentId_fld"))
        self.formLayout.setWidget(11, QtGui.QFormLayout.FieldRole, self.studentId_fld)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtGui.QDialogButtonBox(NewMember)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(NewMember)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), NewMember.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), NewMember.reject)
        QtCore.QMetaObject.connectSlotsByName(NewMember)
        NewMember.setTabOrder(self.surName_fld, self.givenNames_fld)
        NewMember.setTabOrder(self.givenNames_fld, self.preferredName_fld)
        NewMember.setTabOrder(self.preferredName_fld, self.gender_fld)
        NewMember.setTabOrder(self.gender_fld, self.birthDate_fld)
        NewMember.setTabOrder(self.birthDate_fld, self.streetAddress_fld)
        NewMember.setTabOrder(self.streetAddress_fld, self.postalCode_fld)
        NewMember.setTabOrder(self.postalCode_fld, self.city_fld)
        NewMember.setTabOrder(self.city_fld, self.phone_fld)
        NewMember.setTabOrder(self.phone_fld, self.email_fld)
        NewMember.setTabOrder(self.email_fld, self.department_comboBox)
        NewMember.setTabOrder(self.department_comboBox, self.studentId_fld)
        NewMember.setTabOrder(self.studentId_fld, self.username_fld)
        NewMember.setTabOrder(self.username_fld, self.makePhux_CheckBox)
        NewMember.setTabOrder(self.makePhux_CheckBox, self.buttonBox)

    def retranslateUi(self, NewMember):
        NewMember.setWindowTitle(_translate("NewMember", "Dialog", None))
        self.efternamnLabel.setText(_translate("NewMember", "Efternamn", None))
        self.allaFRnamnLabel.setText(_translate("NewMember", "Alla förnamn", None))
        self.tilltalsnamnLabel.setText(_translate("NewMember", "Tilltalsnamn", None))
        self.kNLabel.setText(_translate("NewMember", "Kön", None))
        self.birthDateLabel.setText(_translate("NewMember", "Födelsedatum", None))
        self.adressLabel.setText(_translate("NewMember", "Gatuadress", None))
        self.postnummerLabel.setText(_translate("NewMember", "Postnummer", None))
        self.postanstaltLabel.setText(_translate("NewMember", "Postanstalt", None))
        self.telefonLabel.setText(_translate("NewMember", "Telefon", None))
        self.emailLabel.setText(_translate("NewMember", "Email", None))
        self.avdelningLabel.setText(_translate("NewMember", "Avdelning", None))
        self.anvNdarnamnLabel.setText(_translate("NewMember", "Användarnamn", None))
        self.gRTillPhuxLabel.setText(_translate("NewMember", "Gör till Phux", None))
        self.studentId_label.setText(_translate("NewMember", "Studienummer", None))

